name: corsac_di
version: 0.1.0-dev
description: Dependency Injection container.
author: Anatoly Pulyaevskiy <anatoly.pulyaevskiy@gmail.com>
homepage: https://github.com/corsac-dart/di

environment:
  sdk: '>=1.9.0 <2.0.0'

dependencies:
  dotenv: "^0.1.3+3"

dev_dependencies:
  test: "^0.12.4+7"
  dart_coveralls: "^0.4.0"
