name: 'dart_di'
version: 0.1.0
description: DI container for Dartlang
author: Anatoly Pulyaevskiy <email@example.com>
homepage: https://github.com/pulyaevskiy/dart-di

environment:
  sdk: '>=1.9.0 <2.0.0'

dev_dependencies:
  test: "^0.12.4+7"
